### ISSUE TITLE
现在是停止维护了吗

### ISSUE THREAD

**Issue by DaKMaple** [bigintpro/csdn_downloader#1]
现在是停止维护了吗

**Comment by HollowGL** [comment]
我一开始用PC上的Edge浏览器打开网址，能访问、登录，但不能正常运行，但发现安卓版的Edge打开是正常的。
然后我又尝试了chrome，发现也正常，并且最终用它下载了所需文件。

**Comment by bigintpro** [comment]
还是正常的呀，现在都支持文章下载了

**Comment by bigintpro** [comment]
推荐使用chrome

**Comment by HollowGL** [comment]
> 我一开始用PC上的Edge浏览器打开网址，能访问、登录，但不能正常运行，但发现安卓版的Edge打开是正常的。 然后我又尝试了chrome，发现也正常，并且最终用它下载了所需文件。

我的问题，清除了一下浏览器缓存和cookie，pc的Edge也正常了。可能是我的浏览器插件引起的故障。

**Comment by bigintpro** [comment]
偶尔维护一下
