### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by L1ttleB1rd** [bigintpro/csdn_downloader#10]
我有一个文件下载一直0%,已经过去一天了,很小的一个文件
![V2LL5 {STB {@V85((I1~SL](https://github.com/bigintpro/csdn_downloader/assets/132981371/20406763-3897-43b7-b73d-a8af3308693a)

**Comment by bigintpro** [comment]
已经好了

**Comment by bigintpro** [comment]
已经好了
