### ISSUE TITLE
收费比csdn还高

### ISSUE THREAD

**Issue by Readme0** [bigintpro/csdn_downloader#13]
不能理解

**Comment by DreamerLS1994** [comment]
jerrycoding.com 看广告免费下

**Comment by bigintpro** [comment]
![image](https://github.com/bigintpro/csdn_downloader/assets/94162340/2eb804be-03ae-4781-919f-fcc17399ca20)
这个叫免费下载吗？

**Comment by bigintpro** [comment]
我也想免费呀，但是做不到呀，只能做到低价，你说贵的同学，麻烦把具体的下载地址贴出来，我们马上整改，能做到最低价

**Comment by DreamerLS1994** [comment]
![image](https://github.com/bigintpro/csdn_downloader/assets/31441636/c49d656d-e180-481d-86c1-5b29e7fe986f)
