### ISSUE TITLE
通过推荐地址进入下载，已经被骗！！

### ISSUE THREAD

**Issue by Grozta** [bigintpro/csdn_downloader#18]
![image](https://github.com/bigintpro/csdn_downloader/assets/48401924/61478667-7b52-47fb-86b2-402563cbb715)
我是通过这个入口进入下载页面的，提供scdn的下载地址，他会让你付款。
![image](https://github.com/bigintpro/csdn_downloader/assets/48401924/5845be6a-6b30-4367-ae19-5dde05b54084)
由于第一次使用，需要扫码付款。此时通过扫码付款。发现你注册的账户不会到账。
然后我又去支付宝留言，人家也会回复，但是会很长很长时间才会回复。大概每次回复在半天天左右的时间。也就回复了一次，然后没下文了，记住通过扫码交易的钱就不可能退回。
这次算是长了个教训。
所以。大家别被骗了。骗子，骗子。骗子死全家
![image](https://github.com/bigintpro/csdn_downloader/assets/48401924/b0edf2ea-8fe3-46e3-b6be-4a4e6043db2e)

**Comment by bigintpro** [comment]
不存在骗人的情况，已经处理好了，支付超期了，再支付是不会到账的

**Comment by Grozta** [comment]
确实没骗，现在是到账了。这都多长时间了，我去拼多多都下载完毕了，你给我说到账了。
