### ISSUE TITLE
这个项目只是做宣传的吧？啥也木有。

### ISSUE THREAD

**Issue by vagra** [bigintpro/csdn_downloader#2]

**Comment by bigintpro** [comment]
你可以通过项目代码构建出来的网站，体验一下，如果觉得可以，可以申请源码，目前源码太多了，源码主要是java写的

**Comment by bigintpro** [comment]
后期有时间，我一个一个传上去好了

**Comment by yangmeiooo** [comment]
@bigintpro  三连到位了，期待源码

**Comment by imyyer** [comment]
> 后期有时间，我一个一个传上去好了

能否给我源码？可以有偿

**Comment by iridiumgithub** [comment]
@bigintpro 你好，可否申请源码，assert文件中的jar包无法找到

**Comment by bigintpro** [comment]
> 找到

assert文件中的jar包无法找到是什么意思？

**Comment by jt-z** [comment]
没有源码，看了下源码发现没有全部开源，可否申请源码？

**Comment by 12471220** [comment]
使用自己的账号下载资源然后做代下载收费？

**Comment by bigintpro** [comment]
都是通过第三方系统获取的资源，具体源码只有调用api接口文档
