### ISSUE TITLE
为什么我的显示要收费

### ISSUE THREAD

**Issue by xk-mt** [bigintpro/csdn_downloader#22]
![image](https://github.com/bigintpro/csdn_downloader/assets/77874955/c41c4db1-b112-40a1-8de9-24ecb20e323a)

**Comment by bigintpro** [comment]
我也不想收费，但是再大的能力，也经不起天天撸羊毛呀，所以想了一个折中的办法，收低费的方式处理，不求盈利，保持平衡，过几天费用还要往下降一降，最终逐步实现几乎免费

**Comment by xk-mt** [comment]
原来如此，谢谢大佬
