### ISSUE TITLE
what‘s up!How can I get your code?

### ISSUE THREAD

**Issue by Zhanglaodi** [bigintpro/csdn_downloader#4]
Recently I saw your project from telegram channel, open your project found that download files need to be charged and the article is also charged. Perhaps this is your security policy to prevent the site from being abused. How can I get your code?

**Comment by bigintpro** [comment]
code is waiting to upload

**Comment by jiyupixiu** [comment]
艸，收费了

**Comment by Zhanglaodi** [comment]
Not open source

**Comment by jepen0204** [comment]
这是广告

**Comment by 2100709717** [comment]
4月份说代码在上传这都8月底了，还没见代码

**Comment by itsdapi** [comment]
这个b价格是怎么计算的，90块的价格不如我去开个csdn会员

**Comment by bigintpro** [comment]
能发一下，具体下载资源地址吗

**Comment by bigintpro** [comment]
已经开始上传代码了

**Comment by itsdapi** [comment]
> 能发一下，具体下载资源地址吗

https://blog.csdn.net/eguid/category_12432053.html
不过后面我去淘宝找了个一日会员之后才发现，这个专栏需要单独付费的，我言语说的有些重了😨
