### ISSUE TITLE
收费了？？就想下载个QT助手，艸

### ISSUE THREAD

**Issue by jiyupixiu** [bigintpro/csdn_downloader#6]

**Comment by bigintpro** [comment]
之前是不收费的，实在是吃不消成本的压力，用爱发电只能一会会，所以选择长期坚持低价，市面上有更加便宜的，告诉我，我就能做的更低，唯一的想法，不求盈利，也不能亏本，仅此而已

**Comment by bigintpro** [comment]
欢迎赐教

**Comment by jiyupixiu** [comment]
1,不看色情书籍和音像;2,不要过多的性幻想;3,多做户外运动以释放冲动;4,寻找一些有兴趣的事情去钻研,转移对性的好奇和心理依赖;5,转移兴趣,多接触积极向上的健康事物



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月13日(周四) 上午8:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bigintpro/csdn_downloader] 收费了？？就想下载个QT助手，艸 (Issue #6)




 
之前是不收费的，实在是吃不消成本的压力，用爱发电只能一会会，所以选择长期坚持低价，市面上有更加便宜的，告诉我，我就能做的更低，唯一的想法，不求盈利，也不能亏本，仅此而已
